---
title: "first-analysis"
author: "rfleeman95"
date: "2020-08-27"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
# Becca's Example for JC

## Open Libraries
```{r message = FALSE}
library(ggplot2)
library(factoextra)
library(mixOmics)
library(ropls)
library(dplyr)
```

## Set working directory and prep data
```{r}
setwd("/Users/BeccaFleeman/Box Sync/Proctor_Lab/Computational")
My_csv<-read.csv("Fleeman_Dennis_Data.csv",header=T,stringsAsFactors = F)

My_csv_quant <- My_csv[,2:25]
PC<-prcomp(My_csv_quant,scale=TRUE)
fviz_eig(PC)

class <- My_csv$Class[1:48]
unique(class)
My_csv_PC<-data.frame(PC$x,class)
```

## Plot PCA and Loadings for PC1
```{r}
ggplot(My_csv_PC,aes(x=PC1,y=PC2,col=class))+
  theme_set(theme_grey() + theme(legend.key=element_blank())) +
  geom_point(size=3,alpha=0.8) +
  theme(axis.text.y=element_text(colour="black",size=13))+
  theme(axis.text.x=element_text(colour="black",size=13))+
  theme(axis.title.y=element_text(size=12))+
  theme(axis.title.x=element_text(size=12))+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(axis.line = element_line(colour = "black",size=0.5))+    
  theme(legend.title = element_blank())+
  theme(legend.key.size = unit(0,'lines'))+
  theme(legend.justification = c(0,1), legend.position = c(0.01,1))+
  geom_hline(yintercept = 0, linetype="dashed", color="black",size=0.5)+
  geom_vline(xintercept = 0,linetype="dashed",color="black",size=0.5)+
  xlim(-10,10)+
  ylim(-10,10)+
  scale_colour_manual(values = c("pink","green"))

Loadings_PC1=PC$rotation[,1]
Loadings_PC1=sort(Loadings_PC1,decreasing=TRUE)
PC1Length <- length(Loadings_PC1)
Load_PC1=as.matrix(Loadings_PC1[1:PC1Length])
Load_PC1=t(Load_PC1)
barplot(Load_PC1,col="grey89",las=2,ylim=c(-0.4,0.4))
abline(h=0)
```

## Prep for PLSDA
```{r}
class<-as.factor(class)
k_folds <- 3
n_LV <- 1:5 
nrepeats <- 1:10 
nrepeat_results <- matrix(NA, ncol=5,nrow=30) 
error_groups=matrix(1:30, ncol=3, nrow=10,byrow = TRUE) 
for(n in nrepeats){
  folds_i <- sample(rep(1:k_folds, length.out = nrow(My_csv_quant)))
  cv_error <- matrix(NA, nrow = k_folds, ncol = length(n_LV))
   for (k in 1:k_folds) {
    test_i <- which(folds_i == k) 
    train_set <- My_csv_quant[-test_i, ] 
    test_set <- My_csv_quant[test_i, ] 
    condition_test <- class[test_i] 
    condition_train <- class[-test_i] 
    for (i in n_LV){
      PLSDA_train_iLVs <-  opls(train_set, condition_train, predI = 1, orthoI = (i-1), fig.pdfC=NULL, info.txtC=NULL, scaleC='standard', crossvalI=8)
      predictions <- predict(PLSDA_train_iLVs, test_set)
      cv_error[k,i] <- 1-mean(as.numeric(condition_test==predictions))
    }}
  nrepeat_results[error_groups[n,],1:5] <- cv_error
}

CVrepeated_error_averages <- matrix(NA,ncol=1,nrow=5) 
for (i in 1:ncol(nrepeat_results)){
  CVrepeated_error_averages[i,1] <- mean(nrepeat_results[,i])
}

plot(CVrepeated_error_averages[,1],main="Classification Error, 3-fold CV repeated 10 times", xlab="Latent Variable #", ylab="Classification error rate",ylim=c(0,1)) 
lines(n_LV, 
      CVrepeated_error_averages[,1], lwd = 2)
```

## Run PLSDA and plot PLSDA, Loadings, and VIPs
```{r}
oplsda<-opls(My_csv_quant,y=class,predI=1,orthoI=1,crossvalI=6)

Scores <- getScoreMN(oplsda)
oScores <- oplsda@orthoScoreMN
Scores_Class <- data.frame(Scores, oScores, My_csv$Class)
colnames(Scores_Class)<- c("LV1", "o1", "Class") #add as many o's as needed here

ggplot(Scores_Class,aes(x=LV1,y=o1,col=Class))+
  #theme_set(theme_gray() + theme(legend.key=element_blank())) +
  geom_point(size=2,alpha=0.8)+ 
  theme(axis.text.y=element_text(colour="black",size=12))+
  theme(axis.text.x=element_text(colour="black",size=12))+
  theme(axis.title.y=element_text(size=12))+
  theme(axis.title.x=element_text(size=12))+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(axis.line = element_line(colour = "black",size=0.5))+
  theme(legend.title=element_blank())+
  theme(legend.key.size = unit(0, 'line'))+ ##
  theme(legend.justification=c(0,1), legend.position=c(0.02,.98))+
  theme(legend.text=element_text(size=12))+
  scale_colour_manual(values = c("pink","green"))+ #need to label accordingly
  geom_hline(yintercept=0, linetype="dashed", 
             color = "black", size=0.5)+
  geom_vline(xintercept = 0, linetype="dashed", 
             color = "black", size=0.5)+
  stat_ellipse(type = "t")+ #default 95% confidence ellipse
  xlim(-12,12)+
  ylim(-12,12)+
  xlab("Scores on LV 1 (25.1%)") +     #change this to match input LV!!!
  ylab("Scores on LV 2 (34.7)")+     #change this to match input LV!!!
  theme(plot.title = element_blank()) +
  theme( panel.background = element_rect(colour = "black", size=1))

Load<-getLoadingMN(oplsda)
Loadsort<-sort(Load,decreasing=TRUE)
Loading<-t(Load)
barplot(Loading, col="pink", las=2, ylim=c(-0.2,0.4), ylab="LV1 (Component) 25.1%", font.lab=2)
abline(h=0)

VIP<-getVipVn(oplsda)
VIPsort=sort(VIP,decreasing=TRUE)
barplot(VIPsort, col="pink", las=2, ylim=c(0,2), main= "VIPs", cex.main=1.5, ylab="LV1 (Component) 25.1%", font.lab=2)
abline(h=1)
abline(h=0)

VIPmatrix <- as.data.frame(VIP)
orderedVIPmatrix <- as.data.frame(VIPmatrix[order(VIP),])
```

